apiVersion: v1
data:
  mapRoles: |
    - groups:  
      - system:masters
        rolearn: arn:aws:iam::260718118626:role/UdacityFlaskDeployCBKubectlRole
        username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::260718118626:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-MgsgS4tdj8ub
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-11T08:04:22Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1250"
  uid: 21db5939-db31-41a9-b22c-e1deac949e6b
